### PR TITLE
Add bindep.txt file

### PR DESCRIPTION
**Pull request by pabelanger**
We'll use this for releasenote jobs.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 683928eee8f79d5d8167c8f3c88c80fd67a0d471

**Comment by pabelanger** [comment]
recheck

**Comment by mhuin** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
