### PR TITLE
Add tox -elinters support

### PR DESCRIPTION
**Pull request by pabelanger**
This is the first entry point to use tox.ini, this allows us drop the
dependency on sf-jobs, since it does most of this.  For now, we are
doing flake8, however we really need to have a discussion on the PTI for
ansible-network. To help ensure all roles are testing the same way.

Depends-On: https://github.com/ansible-network/ansible-zuul-jobs/pull/39
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Review by rcarrillocruz — APPROVED** [review]

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 41df289b21950af84a81f982055433c35a73eac5

**Review by rcarrillocruz — APPROVED** [review]

**Pull request merged**
