### PR TITLE
Add unconfigure hooks to delete

### PR DESCRIPTION
**Pull request by rcarrillocruz**

### CODE REVIEW

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Review by pabelanger — APPROVED** [review]

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Pull request merged**
